### ISSUE TITLE
I am curious about the motivation of the project

### ISSUE THREAD

**Issue by JasonYangShadow** [nh13/conda-env-builder#16]
This is not an issue. I am just curious about the motivation of this project. I also suffered issues when installing bio tools inside the same namespace, for example, if I install GATK4/Picard requiring openjdk8 first, then install Trinity requiring openjdk7, the default higher version of JDK is overwritten by the older version, then Picard is corrupted. Basically, this can be solved via installing Trinity first then Picard, at last, the openjdk8 will be kept and there will be no issues. 

Did you know the following project: 
https://github.com/conda-tools/conda-execute

I'd like to help if you can share with me more about the issues encountered. 
Thanks!

**Comment by nh13** [comment]
I tried to document [why in this link](https://github.com/nh13/conda-env-builder#why), but basically I had two issues:
1. I wanted to support multiple conda enviornments in one YAML/specification file, as I frequently have packages that cannot be installed in the same environment (eg. Python 2.7 vs Python 3.6)
2. I wanted to specify packages across multiple conda environments, but remove biolerplate and duplicate specifications.  I solved this through environment inheritance

In your case, I think you want to specify not only GATK4/Picard and Trinity, but specify the openjdk version when you install them.  You'd install multiple packages at the same time and so the solver would "do the right thing".  I don't think the issue you're facing inherently needs `conda-env-builder`.

The tool you linked (conda-execute) looks like it works only for python, so that's a limiting use case.  I can see many others but that's beyond the scope of this issue.
